base:
    seed: &seed 42
model:
    type: Llama
    path: /root/autodl-tmp/workdir/llmc/base_models/meta-llama/Meta-Llama-3-8B/LLM-Research/Meta-Llama-3-8B
    torch_dtype: auto
calib:
    name: wikitext2
    download: False
    path: /root/autodl-tmp/dataset/wikitext_offline
    n_samples: 128
    bs: 1
    seq_len: 512
    preproc: txt_general_preproc
    seed: *seed
eval:
    eval_pos: [transformed]
    name: [wikitext2]
    download: False
    bs: 1
    path: /root/autodl-tmp/dataset/wikitext_offline
    seq_len: 2048
sparse:
    method: ShortGPT
    weight:
        # sparsity: 0.5
        n_prune_layers: 9
        # bit: 4
        # symmetric: true
        # need_pack: false
        # granularity: per_group
        # group_size: 128
    sparsity_out: False
save:
    # save_trans: False
    save_sgl: True
    save_path: /root/autodl-tmp/model_save/llama3_8b_new

