base:
    seed: &seed 0
model:
    type: Llama
    path: /root/autodl-tmp/workdir/llmc/base_models/meta-llama/Meta-Llama-3-8B/LLM-Research/Meta-Llama-3-8B
    torch_dtype: auto
calib:
    name: wikitext2
    download: False
    n_samples: 128
    path: /root/autodl-tmp/dataset/wikitext_offline
    bs: 1
    seq_len: 2048
    preproc: wikitext2_gptq
    seed: *seed
eval:
    eval_pos: [fake_quant]
    name: wikitext2
    download: False
    path: /root/autodl-tmp/dataset/wikitext_offline
    bs: 1
    seq_len: 2048
    inference_per_block: False
quant:
    method: GPTQ
    weight:
        bit: 4
        symmetric: True
        granularity: per_group
        group_size: 128
        need_pack: True
    special:
        actorder: True
        static_groups: True
        percdamp: 0.01
        blocksize: 128
        true_sequential: True
    quant_out: True
save:
    # save_vllm: True
    save_sgl: True
    save_path: /root/autodl-tmp/model_save/llama3_8b_new
