base:
    seed: &seed 42
model:
    type: Llama
    path: /root/autodl-tmp/workdir/llmc/base_models/meta-llama/Meta-Llama-3-8B/LLM-Research/Meta-Llama-3-8B
    torch_dtype: auto
calib:
    name: wikitext2
    download: False
    path: /root/autodl-tmp/dataset/wikitext_offline
    n_samples: 512
    bs: 1
    seq_len: 512
    preproc: txt_general_preproc
    seed: *seed
eval:
    eval_pos: [fake_quant]
    name: wikitext2
    download: False
    path: /root/autodl-tmp/dataset/wikitext_offline
    bs: 1
    seq_len: 2048
quant:
    method: SmoothQuant
    weight:
        bit: 8
        symmetric: True
        granularity: per_channel
    act:
        bit: 8
        symmetric: True
        granularity: per_token
save:
    save_sgl: True
    save_path: /root/autodl-tmp/model_save/llama3_8b_new
